# pnpm workspace configuration for platform-frontend monorepo
packages:
  # Frontend applications (Docker containers)
  - 'apps/*'
  - 'apps/*/ui'
  # Shared packages (internal only, not published)
  - 'packages/*'
